/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/public/models/hologram_projector_with_hologram.glb --types 
Author: t.flores (https://sketchfab.com/t.flores)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hologram-projector-with-hologram-ca0a3bc92a3d4a3f9b0fa19cbc73b420
Title: Hologram projector with hologram
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFAction = any

type GLTFResult = GLTF & {
  nodes: {
    Cube__0: THREE.Mesh
    Cylinder217_Hologram_0: THREE.Mesh
    Cylinder218_Hologram_0: THREE.Mesh
    Cylinder219_Hologram_0: THREE.Mesh
    Cylinder220_Hologram_0: THREE.Mesh
    Cylinder221_Hologram_0: THREE.Mesh
    Cylinder222_Hologram_0: THREE.Mesh
  }
  materials: {
    Cube__0: THREE.MeshStandardMaterial
    Hologram: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/hologram_projector_with_hologram_opt.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Cube__0.geometry} material={materials.Cube__0} position={[0, 11.517, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder217_Hologram_0.geometry} material={materials.Hologram} position={[0, -137.378, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={136.693} />
        <mesh geometry={nodes.Cylinder218_Hologram_0.geometry} material={materials.Hologram} position={[0, -69.461, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={133.389} />
        <mesh geometry={nodes.Cylinder219_Hologram_0.geometry} material={materials.Hologram} position={[0, -69.461, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={133.389} />
        <mesh geometry={nodes.Cylinder220_Hologram_0.geometry} material={materials.Hologram} position={[0, -60.022, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={133.389} />
        <mesh geometry={nodes.Cylinder221_Hologram_0.geometry} material={materials.Hologram} position={[0, -8.513, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={66.535} />
        <mesh geometry={nodes.Cylinder222_Hologram_0.geometry} material={materials.Hologram} position={[0, -137.378, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={136.693} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/hologram_projector_with_hologram.glb')
