/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/public/models/monolith.glb --types 
Author: barbodoji (https://sketchfab.com/barbodoji)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monolith-47ea90af1f9c4893b42f06cb790857f4
Title: monolith
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFAction = any

type GLTFResult = GLTF & {
  nodes: {
    Monolith_Monolith_0: THREE.Mesh
    Monolith_Monolith_0_1: THREE.Mesh
    Monolith_Monolith_0_2: THREE.Mesh
    Monolith_Monolith_0_3: THREE.Mesh
  }
  materials: {
    Monolith: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/monolith_opt.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Monolith_Monolith_0.geometry} material={materials.Monolith} />
          <mesh geometry={nodes.Monolith_Monolith_0_1.geometry} material={materials.Monolith} />
          <mesh geometry={nodes.Monolith_Monolith_0_2.geometry} material={materials.Monolith} />
          <mesh geometry={nodes.Monolith_Monolith_0_3.geometry} material={materials.Monolith} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/monolith_opt.glb')
