/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/public/models/sci-fi_based_server_racks.glb --types 
Author: Inditrion Dradnon (https://sketchfab.com/dradnon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-based-server-racks-f2a7e5fc233b4dd0aab0841495a8506b
Title: Sci-Fi Based Server Racks
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFAction = any

type GLTFResult = GLTF & {
  nodes: {
    MaterialFBXASC032FBXASC0352142150880: THREE.Mesh
    MaterialFBXASC032FBXASC0352142146802: THREE.Mesh
    ORDNUNGSKRAFTFBXASC032Graviton: THREE.Mesh
    MaterialFBXASC032FBXASC0352142150880_1: THREE.Mesh
    ORDNUNGSKRAFTFBXASC032Graviton_1: THREE.Mesh
    MaterialFBXASC032FBXASC0352142146802_1: THREE.Mesh
    LIGHTKRAFTFBXASC032GRAVITONFBXASC032: THREE.Mesh
    MaterialFBXASC032FBXASC0352142150880_2: THREE.Mesh
    ORDNUNGSKRAFTFBXASC032Graviton_2: THREE.Mesh
    MaterialFBXASC032FBXASC0352142146802_2: THREE.Mesh
    MaterialFBXASC032FBXASC03511298: THREE.Mesh
    MaterialFBXASC032FBXASC0352142150880_3: THREE.Mesh
    MaterialFBXASC032FBXASC0352142148579: THREE.Mesh
    MaterialFBXASC032FBXASC0352142147152: THREE.Mesh
    MaterialFBXASC032FBXASC0352142148090: THREE.Mesh
    ORDNUNGSKRAFTFBXASC032Graviton_3: THREE.Mesh
    MaterialFBXASC032FBXASC0352142146802_3: THREE.Mesh
    MaterialFBXASC032FBXASC0352142150880_4: THREE.Mesh
  }
  materials: {
    MaterialFBXASC032FBXASC0352142150880: THREE.MeshStandardMaterial
    MaterialFBXASC032FBXASC0352142146802: THREE.MeshStandardMaterial
    ORDNUNGSKRAFTFBXASC032Graviton: THREE.MeshStandardMaterial
    LIGHTKRAFTFBXASC032GRAVITONFBXASC032: THREE.MeshStandardMaterial
    MaterialFBXASC032FBXASC03511298: THREE.MeshStandardMaterial
    MaterialFBXASC032FBXASC0352142148579: THREE.MeshStandardMaterial
    MaterialFBXASC032FBXASC0352142147152: THREE.MeshStandardMaterial
    MaterialFBXASC032FBXASC0352142148090: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/sci-fi_server_racks_opt.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-118.503, 12.392, 70.682]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-1, 1, 0.399]}>
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0352142150880.geometry} material={materials.MaterialFBXASC032FBXASC0352142150880} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0352142146802.geometry} material={materials.MaterialFBXASC032FBXASC0352142146802} />
            <mesh geometry={nodes.ORDNUNGSKRAFTFBXASC032Graviton.geometry} material={materials.ORDNUNGSKRAFTFBXASC032Graviton} />
          </group>
          <group position={[-106.133, 12.392, 70.682]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-1, 1, 0.399]}>
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0352142150880_1.geometry} material={materials.MaterialFBXASC032FBXASC0352142150880} />
            <mesh geometry={nodes.ORDNUNGSKRAFTFBXASC032Graviton_1.geometry} material={materials.ORDNUNGSKRAFTFBXASC032Graviton} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0352142146802_1.geometry} material={materials.MaterialFBXASC032FBXASC0352142146802} />
            <mesh geometry={nodes.LIGHTKRAFTFBXASC032GRAVITONFBXASC032.geometry} material={materials.LIGHTKRAFTFBXASC032GRAVITONFBXASC032} />
          </group>
          <group position={[-93.763, 12.392, 70.682]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-1, 1, 0.399]}>
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0352142150880_2.geometry} material={materials.MaterialFBXASC032FBXASC0352142150880} />
            <mesh geometry={nodes.ORDNUNGSKRAFTFBXASC032Graviton_2.geometry} material={materials.ORDNUNGSKRAFTFBXASC032Graviton} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0352142146802_2.geometry} material={materials.MaterialFBXASC032FBXASC0352142146802} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC03511298.geometry} material={materials.MaterialFBXASC032FBXASC03511298} />
          </group>
          <group position={[-81.393, 12.392, 69.066]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-1, 1, 0.399]}>
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0352142150880_3.geometry} material={materials.MaterialFBXASC032FBXASC0352142150880} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0352142148579.geometry} material={materials.MaterialFBXASC032FBXASC0352142148579} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0352142147152.geometry} material={materials.MaterialFBXASC032FBXASC0352142147152} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0352142148090.geometry} material={materials.MaterialFBXASC032FBXASC0352142148090} />
            <mesh geometry={nodes.ORDNUNGSKRAFTFBXASC032Graviton_3.geometry} material={materials.ORDNUNGSKRAFTFBXASC032Graviton} />
            <mesh geometry={nodes.MaterialFBXASC032FBXASC0352142146802_3.geometry} material={materials.MaterialFBXASC032FBXASC0352142146802} />
          </group>
          <mesh geometry={nodes.MaterialFBXASC032FBXASC0352142150880_4.geometry} material={materials.MaterialFBXASC032FBXASC0352142150880} position={[-67.697, 12.392, 70.682]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-1, 1, 0.399]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/sci-fi_based_server_racks.glb')
